---
name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

env:
  # Common versions
  GO_VERSION: '1.22'
  GOLANGCI_VERSION: 'v1.57.2'

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: Run linters
        uses: golangci/golangci-lint-action@v4
        with:
          version: ${{ env.GOLANGCI_VERSION }}

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install Go
  #       if: success()
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: ${{ env.GO_VERSION }}
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Run tests
  #       run: go test -v -covermode=count ./pkg/...

  # coverage:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install Go
  #       if: success()
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: ${{ GO_VERSION }}
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Calc coverage
  #       run: |
  #         go test -v -covermode=count -coverprofile=coverage.out
  #     - name: Convert coverage.out to coverage.lcov
  #       uses: jandelgado/gcov2lcov-action@v1.0.6
  #     - name: Coveralls
  #       uses: coverallsapp/github-action@v1.1.2
  #       with:
  #         github-token: ${{ secrets.github_token }}
  #         path-to-lcov: coverage.lcov
